function demoCarbonTimestamp(dateStr) {
  return { toMillis: function () { return new Date(dateStr).getTime(); } };
}

window.CARBON_LISTINGS = [
  {
    id: 'cc-demo-001',
    supplierUID: 'demo',
    supplierName: 'Redwood Carbon Partners',
    contactEmail: 'credits@redwoodcarbon.com',
    projectName: 'North Coast Forest Recovery',
    projectType: 'forestry',
    standard: 'CAR',
    vintageYear: 2023,
    volumeTonnes: 4200,
    pricePerTonne: 34,
    cobenefits: ['habitat', 'watershed', 'community jobs'],
    projectLocation: 'Humboldt County, CA',
    registryUrl: 'https://registry.climateactionreserve.org',
    documents: ['https://registry.climateactionreserve.org'],
    verified: true,
    status: 'active',
    createdAt: demoCarbonTimestamp('2026-02-18')
  },
  {
    id: 'cc-demo-002',
    supplierUID: 'demo',
    supplierName: 'Willamette Biochar Cooperative',
    contactEmail: 'info@willamettebiochar.coop',
    projectName: 'Willamette Valley Biochar Credits',
    projectType: 'biochar',
    standard: 'VCS',
    vintageYear: 2024,
    volumeTonnes: 950,
    pricePerTonne: 68,
    cobenefits: ['soil health', 'air quality'],
    projectLocation: 'Marion County, OR',
    registryUrl: 'https://registry.verra.org',
    documents: ['https://registry.verra.org'],
    verified: true,
    status: 'active',
    createdAt: demoCarbonTimestamp('2026-03-03')
  },
  {
    id: 'cc-demo-003',
    supplierUID: 'demo',
    supplierName: 'Yakima Soil Carbon',
    contactEmail: 'credits@yakimacarbon.org',
    projectName: 'Yakima Regenerative Soil Program',
    projectType: 'soil_carbon',
    standard: 'ACR',
    vintageYear: 2022,
    volumeTonnes: 1800,
    pricePerTonne: 27,
    cobenefits: ['water retention', 'biodiversity'],
    projectLocation: 'Yakima County, WA',
    registryUrl: 'https://acr2.apx.com',
    documents: ['https://acr2.apx.com'],
    verified: false,
    status: 'active',
    createdAt: demoCarbonTimestamp('2026-01-29')
  },
  {
    id: 'cc-demo-004',
    supplierUID: 'demo',
    supplierName: 'Inland Methane Capture',
    contactEmail: 'sales@inlandmethane.com',
    projectName: 'San Joaquin Dairy Methane Capture',
    projectType: 'methane',
    standard: 'CAR',
    vintageYear: 2023,
    volumeTonnes: 6200,
    pricePerTonne: 22,
    cobenefits: ['odor reduction', 'local air quality'],
    projectLocation: 'Tulare County, CA',
    registryUrl: 'https://registry.climateactionreserve.org',
    documents: ['https://registry.climateactionreserve.org'],
    verified: true,
    status: 'active',
    createdAt: demoCarbonTimestamp('2026-02-05')
  },
  {
    id: 'cc-demo-005',
    supplierUID: 'demo',
    supplierName: 'Cascade Direct Air Capture',
    contactEmail: 'credits@cascadedac.com',
    projectName: 'Cascade DAC Pilot',
    projectType: 'dac',
    standard: 'self_certified',
    vintageYear: 2025,
    volumeTonnes: 320,
    pricePerTonne: 85,
    cobenefits: ['innovation', 'local jobs'],
    projectLocation: 'Klamath County, OR',
    registryUrl: 'https://cascadedac.com/registry',
    documents: ['https://cascadedac.com/registry'],
    verified: false,
    status: 'active',
    createdAt: demoCarbonTimestamp('2026-03-12')
  },
  {
    id: 'cc-demo-006',
    supplierUID: 'demo',
    supplierName: 'Salinas Biochar Projects',
    contactEmail: 'credits@salinasbiochar.com',
    projectName: 'Central Coast Biochar Credits',
    projectType: 'biochar',
    standard: 'GoldStandard',
    vintageYear: 2024,
    volumeTonnes: 1400,
    pricePerTonne: 72,
    cobenefits: ['soil health', 'water conservation', 'fire risk reduction'],
    projectLocation: 'Monterey County, CA',
    registryUrl: 'https://registry.goldstandard.org',
    documents: ['https://registry.goldstandard.org'],
    verified: true,
    status: 'active',
    createdAt: demoCarbonTimestamp('2026-03-26')
  }
];
