window.LISTINGS = [
  {
    id: "cbx-001",
    status: "active",
    producerName: "Valley Carbon Cooperative",
    county: "Fresno",
    producerZip: "93706",
    state: "California",
    optimalRadius: "100",
    feedstock: "Almond Shell",
    availableTonnes: 420,
    minOrderTonnes: 5,
    leadTimeDays: 0,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 365,
    certifications: ["IBI Certified", "California Organic"],
    availableFrom: "2026-03-01",
    availableUntil: "2026-10-31",
    scorecard: {
      carbonContent: 76.2,
      pH: 8.4,
      surfaceArea: 355,
      particleSize: "1-4mm",
      moisture: 7.9,
      ashContent: 11.6,
      electricalConductivity: 0.7,
      labVerified: true
    },
    description:
      "We produce this lot from clean almond shell feedstock sourced within a 60-mile radius of our kiln facility. Our batch is screened for uniform particle size to support consistent field application and blending. Third-party lab results are updated each production run.",
    suitableFor: ["Almond Orchards", "Row Crops", "Pistachio Orchards"],
    transactionsCompleted: 14,
    averageRating: 4.7,
    contactEmail: "info@valleycarboncooperative.com"
  },
  {
    id: "cbx-002",
    status: "active",
    producerName: "Delta Pyro Materials",
    county: "Yolo",
    producerZip: "95616",
    state: "California",
    optimalRadius: "100",
    feedstock: "Rice Husk",
    availableTonnes: 260,
    minOrderTonnes: 5,
    leadTimeDays: 0,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 310,
    certifications: ["OMRI Listed", "IBI Certified"],
    availableFrom: "2026-05-09",
    availableUntil: "2026-11-15",
    scorecard: {
      carbonContent: 68.9,
      pH: 7.8,
      surfaceArea: 298,
      particleSize: "0.5-2mm",
      moisture: 9.2,
      ashContent: 15.3,
      electricalConductivity: 1.1,
      labVerified: true
    },
    description:
      "We convert post-harvest rice husk into a fine, high-silica biochar designed for broadacre and paddy systems. Our operation maintains lot traceability from mill intake through bagging and bulk dispatch. Material is supplied loose bulk or super sacks based on your handling setup.",
    suitableFor: ["Rice", "Row Crops", "Pasture"],
    transactionsCompleted: 9,
    averageRating: 4.4,
    contactEmail: "info@deltapyromaterials.com"
  },
  {
    id: "cbx-003",
    status: "active",
    producerName: "Redwood Soil Carbon",
    county: "Humboldt",
    producerZip: "95501",
    state: "California",
    optimalRadius: "200",
    feedstock: "Wood Chip",
    availableTonnes: 180,
    minOrderTonnes: 5,
    leadTimeDays: 0,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 520,
    certifications: ["IBI Certified"],
    availableFrom: "2026-05-14",
    availableUntil: "2026-12-20",
    scorecard: {
      carbonContent: 81.4,
      pH: 8.9,
      surfaceArea: 402,
      particleSize: "2-6mm",
      moisture: 6.4,
      ashContent: 9.8,
      electricalConductivity: 0.5,
      labVerified: true
    },
    description:
      "We manufacture this wood-chip char from FSC-aligned forest thinning residues and sawmill side streams. Our product is designed for long residence time and high porosity in perennial systems. We publish full scorecards and retain reserve samples for quality audits.",
    suitableFor: ["Grapevine / Vineyards", "Walnut Orchards", "Forestry"],
    transactionsCompleted: 6,
    averageRating: 4.6,
    contactEmail: "info@redwoodsoilcarbon.com"
  },
  {
    id: "cbx-004",
    status: "active",
    producerName: "Sonoma Circular Char",
    county: "Sonoma",
    producerZip: "95401",
    state: "California",
    optimalRadius: "50",
    feedstock: "Vine Pruning",
    availableTonnes: 95,
    minOrderTonnes: 5,
    leadTimeDays: 0,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 610,
    certifications: ["California Organic"],
    availableFrom: "2026-02-10",
    availableUntil: "2026-08-30",
    scorecard: {
      carbonContent: 73.1,
      pH: 8.1,
      surfaceArea: 336,
      particleSize: "1-5mm",
      moisture: 8.8,
      ashContent: 12.9,
      electricalConductivity: 0.9,
      labVerified: true
    },
    description:
      "We produce vine-pruning biochar from estate and neighboring vineyard blocks under a closed-loop program. This material is optimized for vineyard floor incorporation and compost blending. Seasonal production windows are reflected in our listed availability dates.",
    suitableFor: ["Grapevine / Vineyards", "Row Crops"],
    transactionsCompleted: 3,
    averageRating: 4.2,
    contactEmail: "info@sonomacircularchar.com"
  },
  {
    id: "cbx-005",
    status: "active",
    producerName: "Central Coast Nut Carbon",
    county: "Santa Barbara",
    producerZip: "93101",
    state: "California",
    optimalRadius: "none",
    feedstock: "Walnut Shell",
    availableTonnes: 140,
    minOrderTonnes: 5,
    leadTimeDays: 0,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 455,
    certifications: ["OMRI Listed", "California Organic"],
    availableFrom: "2026-03-20",
    availableUntil: "2026-09-25",
    scorecard: {
      carbonContent: 74.6,
      pH: 8.3,
      surfaceArea: 349,
      particleSize: "1-3mm",
      moisture: 7.1,
      ashContent: 10.7,
      electricalConductivity: 0.8,
      labVerified: false
    },
    description:
      "We process cracked walnut shell fractions into a medium-grind biochar for diversified coastal farms. Our batches are blended to maintain stable pH and moisture targets for predictable field performance. Freight coordination is available for palletized and walking-floor deliveries.",
    suitableFor: ["Walnut Orchards", "Pistachio Orchards", "Row Crops"],
    transactionsCompleted: 0,
    averageRating: null,
    contactEmail: "info@centralcoastnutcarbon.com"
  },
  {
    id: "cbx-006",
    status: "active",
    producerName: "Foothill Biomass Exchange",
    county: "El Dorado",
    producerZip: "95667",
    state: "California",
    optimalRadius: "100",
    feedstock: "Wood Chip",
    availableTonnes: 230,
    minOrderTonnes: 5,
    leadTimeDays: 0,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 390,
    certifications: ["IBI Certified", "OMRI Listed", "California Organic"],
    availableFrom: "2026-04-01",
    availableUntil: "2026-11-30",
    scorecard: {
      carbonContent: 79.3,
      pH: 8.6,
      surfaceArea: 371,
      particleSize: "2-5mm",
      moisture: 6.9,
      ashContent: 10.2,
      electricalConductivity: 0.6,
      labVerified: true
    },
    description:
      "We produce this material from mixed hardwood and softwood chips generated through fuel-reduction projects in the foothills. The char is screened for spreader compatibility and low fines content. We support recurring contracts for orchards and annual row-crop programs.",
    suitableFor: ["Almond Orchards", "Row Crops", "Pasture"],
    transactionsCompleted: 12,
    averageRating: 4.8,
    contactEmail: "info@foothillbiomassexchange.com"
  },
  {
    id: "cbx-007",
    status: "active",
    producerName: "San Joaquin Carbon Works",
    county: "Kings",
    producerZip: "93230",
    state: "California",
    optimalRadius: "200",
    feedstock: "Corn Stover",
    availableTonnes: 1800,
    minOrderTonnes: 50,
    leadTimeDays: 7,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 295,
    certifications: ["IBI Certified"],
    availableFrom: "2026-03-01",
    availableUntil: "2026-12-31",
    scorecard: {
      carbonContent: 72.1,
      pH: 8.1,
      surfaceArea: 310,
      particleSize: "2-6mm",
      moisture: 9.2,
      ashContent: 14.3,
      electricalConductivity: 1.1,
      labVerified: true
    },
    description: "High-volume continuous reactor operation producing corn stover biochar for large-scale soil carbon programs and row-crop operations. Minimum 50-tonne orders. Recurring supply contracts available. Rail siding on site for bulk loading. Suitable for carbon credit programs — carbon content independently verified quarterly.",
    suitableFor: ["Row Crops", "Corn", "Pasture", "Wheat"],
    transactionsCompleted: 31,
    averageRating: 4.6,
    contactEmail: "supply@sjcarbonworks.com",
    fairPriceMin: 270,
    fairPriceMax: 320
  },
  {
    id: "cbx-008",
    status: "active",
    producerName: "Klamath Forest Carbon",
    county: "Jackson",
    producerZip: "97520",
    state: "Oregon",
    optimalRadius: "200",
    feedstock: "Forest Residue",
    availableTonnes: 340,
    minOrderTonnes: 10,
    leadTimeDays: 5,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 405,
    certifications: ["IBI Certified"],
    availableFrom: "2026-04-28",
    availableUntil: "2026-11-10",
    scorecard: {
      carbonContent: 77.8,
      pH: 8.7,
      surfaceArea: 286,
      particleSize: "2-8mm",
      moisture: 8.3,
      ashContent: 9.7,
      electricalConductivity: 0.6,
      labVerified: true
    },
    description:
      "Forest-thinning residues converted into a rugged, low-moisture char for remediation blends, composting programs, and broadacre application. This lot is screened for walking-floor delivery and recurring contract fulfillment.",
    suitableFor: ["Forestry", "Remediation", "Pasture"],
    transactionsCompleted: 8,
    averageRating: 4.5,
    contactEmail: "sales@klamathforestcarbon.com"
  },
  {
    id: "cbx-009",
    status: "active",
    producerName: "Willamette Soil Works",
    county: "Marion",
    producerZip: "97301",
    state: "Oregon",
    optimalRadius: "100",
    feedstock: "Hazelnut Shell",
    availableTonnes: 160,
    minOrderTonnes: 5,
    leadTimeDays: 3,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 438,
    certifications: ["OMRI Listed"],
    availableFrom: "2026-05-12",
    availableUntil: "2026-09-30",
    scorecard: {
      carbonContent: 71.5,
      pH: 8.0,
      surfaceArea: 244,
      particleSize: "1-4mm",
      moisture: 7.5,
      ashContent: 11.1,
      electricalConductivity: 0.9,
      labVerified: true
    },
    description:
      "Hazelnut shell biochar milled for row-crop blending, specialty horticulture, and compost enhancement. Lots are packaged for regional distribution and sold in bulk totes or walking-floor shipments.",
    suitableFor: ["Row Crops", "Specialty Crops", "Pasture"],
    transactionsCompleted: 5,
    averageRating: 4.3,
    contactEmail: "hello@willamettesoilworks.com"
  },
  {
    id: "cbx-010",
    status: "active",
    producerName: "Cascade Circular Carbon",
    county: "Kern",
    producerZip: "93307",
    state: "California",
    optimalRadius: "none",
    feedstock: "Pistachio Shell",
    availableTonnes: 275,
    minOrderTonnes: 8,
    leadTimeDays: 4,
    hardFloor: null,
    producerUID: null,
    pricePerTonne: 428,
    certifications: ["IBI Certified", "OMRI Listed"],
    availableFrom: "2026-05-11",
    availableUntil: "2026-12-05",
    scorecard: {
      carbonContent: 75.4,
      pH: 8.5,
      surfaceArea: 332,
      particleSize: "1-5mm",
      moisture: 6.8,
      ashContent: 10.4,
      electricalConductivity: 0.7,
      labVerified: true
    },
    description:
      "Pistachio shell char produced for permanent crop systems and bulk soil blending. Material is moisture-controlled and screened for dependable spreader performance across orchard and reclamation jobs.",
    suitableFor: ["Pistachio Orchards", "Almond Orchards", "Remediation"],
    transactionsCompleted: 11,
    averageRating: 4.7,
    contactEmail: "orders@cascadecircularcarbon.com"
  }
];
