function demoTimestamp(dateStr) {
  return { toMillis: function () { return new Date(dateStr).getTime(); } };
}

window.FEEDSTOCK_YIELD_RATIOS = {
  orchard_prunings: 0.28,
  almond_shells: 0.32,
  pistachio_shells: 0.33,
  walnut_shells: 0.31,
  corn_stover: 0.22,
  rice_husks: 0.35,
  forestry_slash: 0.26,
  logging_residue: 0.27,
  thinning_material: 0.25,
  clean_wood_waste: 0.28,
  construction_wood: 0.27,
  tree_service_chips: 0.26
};

window.FEEDSTOCK_LISTINGS = [
  {
    _id: 'fs-demo-201',
    supplierUID: 'demo',
    supplierName: 'Maria Gutierrez',
    company: 'Gutierrez Family Orchards',
    contactEmail: 'maria@gutierrezorchards.com',
    phone: '',
    supplierType: 'farmer',
    biomassTypes: ['orchard_prunings'],
    biomassType: 'orchard_prunings',
    particleSize: 'chipped',
    contaminationRisk: 'scored',
    contaminationDebris: '2',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: 'fresh',
    moistureContent: '20_30',
    loadingType: 'pile',
    estimatedQuantityTons: 500,
    minimumPickupTons: 40,
    pricePerTon: 20,
    negotiable: true,
    locationZip: '93274',
    harvestDate: '2026-02-20',
    availabilityWindow: 'March–June 2026',
    notes: 'Mixed orchard prunings from 180 acres. Loader on site. Easy truck access off Hwy 99.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-10')
  },
  {
    _id: 'fs-demo-202',
    supplierUID: 'demo',
    supplierName: 'Tom Bergstrom',
    company: 'Sierra Nevada Timber',
    contactEmail: 'tom@snvtimber.com',
    phone: '',
    supplierType: 'sawmill',
    biomassTypes: ['logging_residue'],
    biomassType: 'logging_residue',
    particleSize: 'mixed',
    contaminationRisk: 'scored',
    contaminationDebris: '2',
    contaminationAsh: '3',
    contaminationChemical: '1',
    ageOfMaterial: '6_months',
    moistureContent: '30_40',
    loadingType: 'pile',
    estimatedQuantityTons: 1500,
    minimumPickupTons: 80,
    pricePerTon: 12,
    negotiable: false,
    locationZip: '96002',
    harvestDate: '',
    availabilityWindow: 'Available now',
    notes: 'Pine/fir logging residue from thinning projects. Stored on-site at Redding yard.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-05')
  },
  {
    _id: 'fs-demo-203',
    supplierUID: 'demo',
    supplierName: 'Kevin Park',
    company: 'Bay Area Tree Care',
    contactEmail: 'kevin@batreecare.com',
    phone: '',
    supplierType: 'tree_service',
    biomassTypes: ['tree_service_chips'],
    biomassType: 'tree_service_chips',
    particleSize: 'chipped',
    contaminationRisk: 'scored',
    contaminationDebris: '2',
    contaminationAsh: '3',
    contaminationChemical: '2',
    ageOfMaterial: 'fresh',
    moistureContent: '20_30',
    loadingType: 'loose',
    estimatedQuantityTons: 120,
    minimumPickupTons: 20,
    pricePerTon: 0,
    negotiable: true,
    locationZip: '94607',
    harvestDate: '',
    availabilityWindow: 'Ongoing — weekly batches',
    notes: 'Fresh chips from residential and commercial tree work in Oakland. Mostly oak and eucalyptus.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-20')
  },
  {
    _id: 'fs-demo-204',
    supplierUID: 'demo',
    supplierName: 'Carol Whitfield',
    company: 'Sacramento Clean Demolition',
    contactEmail: 'carol@sacdemolition.com',
    phone: '',
    supplierType: 'recycler',
    biomassTypes: ['clean_wood_waste'],
    biomassType: 'clean_wood_waste',
    particleSize: 'shredded',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '2',
    ageOfMaterial: 'fresh',
    moistureContent: 'under_20',
    loadingType: 'stacked',
    estimatedQuantityTons: 200,
    minimumPickupTons: 30,
    pricePerTon: 10,
    negotiable: true,
    locationZip: '95827',
    harvestDate: '',
    availabilityWindow: 'Available now',
    notes: 'Untreated dimensional lumber and pallets. Clean and sorted for reuse or conversion.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-28')
  },
  {
    _id: 'fs-demo-205',
    supplierUID: 'demo',
    supplierName: 'Dave Schultz',
    company: 'Mendocino Forest Products',
    contactEmail: 'dave@mfpwood.com',
    phone: '',
    supplierType: 'forestry_operator',
    biomassTypes: ['thinning_material'],
    biomassType: 'thinning_material',
    particleSize: 'whole_limbs',
    contaminationRisk: 'scored',
    contaminationDebris: '3',
    contaminationAsh: '3',
    contaminationChemical: '2',
    ageOfMaterial: '6_months',
    moistureContent: '30_40',
    loadingType: 'pile',
    estimatedQuantityTons: 2200,
    minimumPickupTons: 100,
    pricePerTon: 8,
    negotiable: true,
    locationZip: '95482',
    harvestDate: '',
    availabilityWindow: 'Spring–Summer 2026',
    notes: 'Fuel-reduction thinning project. Whole limbs and small diameter stems; some soil contact.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-12')
  },
  {
    _id: 'fs-demo-206',
    supplierUID: 'demo',
    supplierName: 'Priya Nair',
    company: 'Sacramento Valley Rice',
    contactEmail: 'priya@sacvalleyrice.com',
    phone: '',
    supplierType: 'farmer',
    biomassTypes: ['rice_husks'],
    biomassType: 'rice_husks',
    particleSize: 'mixed',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: 'fresh',
    moistureContent: 'under_20',
    loadingType: 'baled',
    estimatedQuantityTons: 450,
    minimumPickupTons: 50,
    pricePerTon: 24,
    negotiable: false,
    locationZip: '95991',
    harvestDate: '2026-10-05',
    availabilityWindow: 'October–December 2026',
    notes: 'Dry rice husks from post-harvest processing. Consistent particle size, baled and ready to load.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-02')
  },
  {
    _id: 'fs-demo-207',
    supplierUID: 'demo',
    supplierName: 'Hector Alvarez',
    company: 'Portland Biomass Aggregators',
    contactEmail: 'hector@pdxbiomass.com',
    phone: '',
    supplierType: 'aggregator',
    biomassTypes: ['clean_wood_waste', 'construction_wood', 'tree_service_chips'],
    biomassType: 'clean_wood_waste',
    particleSize: 'shredded',
    contaminationRisk: 'scored',
    contaminationDebris: '2',
    contaminationAsh: '3',
    contaminationChemical: '2',
    ageOfMaterial: '6_months',
    moistureContent: '20_30',
    loadingType: 'stacked',
    estimatedQuantityTons: 800,
    minimumPickupTons: 60,
    pricePerTon: 14,
    negotiable: true,
    locationZip: '97230',
    harvestDate: '',
    availabilityWindow: 'Available now',
    notes: 'Aggregated clean wood waste from multiple transfer stations. Tested monthly for contaminants.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-18')
  },
  {
    _id: 'fs-demo-208',
    supplierUID: 'demo',
    supplierName: 'Nora Kim',
    company: 'Puget Sound Biomass Brokers',
    contactEmail: 'nora@pugetbrokers.com',
    phone: '',
    supplierType: 'broker',
    biomassTypes: ['orchard_prunings', 'logging_residue'],
    biomassType: 'logging_residue',
    particleSize: 'mixed',
    contaminationRisk: 'scored',
    contaminationDebris: '2',
    contaminationAsh: '3',
    contaminationChemical: '3',
    ageOfMaterial: '6_months',
    moistureContent: '30_40',
    loadingType: 'pile',
    estimatedQuantityTons: 900,
    minimumPickupTons: 75,
    pricePerTon: 16,
    negotiable: true,
    locationZip: '98108',
    harvestDate: '',
    availabilityWindow: 'Available now',
    notes: 'Brokered supply from multiple forest operations in western Washington. Variable moisture and chip size.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-08')
  },
  {
    _id: 'fs-demo-209',
    supplierUID: 'demo',
    supplierName: 'Avery Lewis',
    company: 'Tacoma Reuse Works',
    contactEmail: 'avery@tacomareuse.com',
    phone: '',
    supplierType: 'recycler',
    biomassTypes: ['construction_wood'],
    biomassType: 'construction_wood',
    particleSize: 'coarse_chunks',
    contaminationRisk: 'scored',
    contaminationDebris: '3',
    contaminationAsh: '4',
    contaminationChemical: '3',
    ageOfMaterial: '1_year_plus',
    moistureContent: '20_30',
    loadingType: 'stacked',
    estimatedQuantityTons: 260,
    minimumPickupTons: 40,
    pricePerTon: 5,
    negotiable: true,
    locationZip: '98421',
    harvestDate: '',
    availabilityWindow: 'Spring–Fall 2026',
    notes: 'Reclaimed construction wood. Cleaned and sorted but may include minor fasteners; inspection required.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-25')
  }
];
