function demoTimestamp(dateStr) {
  return { toMillis: function () { return new Date(dateStr).getTime(); } };
}

window.FEEDSTOCK_YIELD_RATIOS = {
  orchard_prunings: 0.28,
  almond_shells: 0.32,
  pistachio_shells: 0.33,
  walnut_shells: 0.31,
  corn_stover: 0.22,
  rice_husks: 0.35,
  forestry_slash: 0.26,
  logging_residue: 0.27,
  thinning_material: 0.25,
  clean_wood_waste: 0.28,
  construction_wood: 0.27,
  tree_service_chips: 0.26
};

window.FEEDSTOCK_LISTINGS = [
  {
    _id: 'fs-demo-001',
    supplierUID: 'demo',
    supplierName: 'Maria Gutierrez',
    company: 'Gutierrez Family Orchards',
    contactEmail: 'maria@gutierrezorchards.com',
    phone: '',
    supplierType: 'farmer',
    biomassTypes: ['orchard_prunings'],
    biomassType: 'orchard_prunings',
    particleSize: 'chipped',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: 'fresh',
    moistureContent: '20_30',
    loadingType: 'pile',
    estimatedQuantityTons: 600,
    minimumPickupTons: 40,
    pricePerTon: 18,
    negotiable: true,
    locationZip: '93274',
    harvestDate: '2026-02-15',
    availabilityWindow: 'March–June 2026',
    notes: 'Almond and walnut mix from 200-acre orchard. Loader on site. Easy truck access off Hwy 99.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-10')
  },
  {
    _id: 'fs-demo-002',
    supplierUID: 'demo',
    supplierName: 'Tom Bergstrom',
    company: 'Sierra Nevada Timber',
    contactEmail: 'tom@snvtimber.com',
    phone: '',
    supplierType: 'sawmill',
    biomassTypes: ['logging_residue'],
    biomassType: 'logging_residue',
    particleSize: 'mixed',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: '6_months',
    moistureContent: '30_40',
    loadingType: 'pile',
    estimatedQuantityTons: 1200,
    minimumPickupTons: 80,
    pricePerTon: 12,
    negotiable: false,
    locationZip: '95667',
    harvestDate: '',
    availabilityWindow: 'Available now',
    notes: 'Mix of pine and fir slash from thinning operations. Material is stored on-site at our El Dorado County yard.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-05')
  },
  {
    _id: 'fs-demo-003',
    supplierUID: 'demo',
    supplierName: 'Kevin Park',
    company: 'Bay Area Tree Care',
    contactEmail: 'kevin@batreecare.com',
    phone: '',
    supplierType: 'tree_service',
    biomassTypes: ['tree_service_chips'],
    biomassType: 'tree_service_chips',
    particleSize: 'chipped',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: 'fresh',
    moistureContent: '20_30',
    loadingType: 'loose',
    estimatedQuantityTons: 80,
    minimumPickupTons: 20,
    pricePerTon: 0,
    negotiable: true,
    locationZip: '94501',
    harvestDate: '',
    availabilityWindow: 'Ongoing — weekly batches',
    notes: 'Fresh chips from residential and commercial tree work in Oakland and Alameda. Free to haul — we just need it gone. Mostly oak and eucalyptus.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-20')
  },
  {
    _id: 'fs-demo-004',
    supplierUID: 'demo',
    supplierName: 'Priya Nair',
    company: 'Sacramento Valley Rice',
    contactEmail: 'priya@sacvalleyrice.com',
    phone: '',
    supplierType: 'farmer',
    biomassTypes: ['rice_husks'],
    biomassType: 'rice_husks',
    particleSize: 'mixed',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: 'fresh',
    moistureContent: 'under_20',
    loadingType: 'baled',
    estimatedQuantityTons: 400,
    minimumPickupTons: 50,
    pricePerTon: 22,
    negotiable: false,
    locationZip: '95616',
    harvestDate: '2026-10-01',
    availabilityWindow: 'October–December 2026',
    notes: 'Dry rice husks from post-harvest processing. Excellent pyrolysis feedstock — very low moisture, consistent particle size. Baled and ready to load.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-01')
  },
  {
    _id: 'fs-demo-005',
    supplierUID: 'demo',
    supplierName: 'Dave Schultz',
    company: 'Mendocino Forest Products',
    contactEmail: 'dave@mfpwood.com',
    phone: '',
    supplierType: 'forestry_operator',
    biomassTypes: ['thinning_material'],
    biomassType: 'thinning_material',
    particleSize: 'whole_limbs',
    contaminationRisk: 'scored',
    contaminationDebris: '3',
    contaminationAsh: '3',
    contaminationChemical: '1',
    ageOfMaterial: '6_months',
    moistureContent: '30_40',
    loadingType: 'pile',
    estimatedQuantityTons: 2000,
    minimumPickupTons: 100,
    pricePerTon: 8,
    negotiable: true,
    locationZip: '95460',
    harvestDate: '',
    availabilityWindow: 'Spring–Summer 2026',
    notes: 'Cal Fire-funded thinning project. Material is whole limbs and small diameter stems, some soil contact. Road access requires high-clearance trucks.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-01-12')
  },
  {
    _id: 'fs-demo-006',
    supplierUID: 'demo',
    supplierName: 'Carol Whitfield',
    company: 'Sonoma Clean Demolition',
    contactEmail: 'carol@sonomaclean.com',
    phone: '',
    supplierType: 'recycler',
    biomassTypes: ['clean_wood_waste'],
    biomassType: 'clean_wood_waste',
    particleSize: 'chipped',
    contaminationRisk: 'scored',
    contaminationDebris: '1',
    contaminationAsh: '2',
    contaminationChemical: '1',
    ageOfMaterial: 'fresh',
    moistureContent: 'under_20',
    loadingType: 'stacked',
    estimatedQuantityTons: 150,
    minimumPickupTons: 30,
    pricePerTon: 15,
    negotiable: true,
    locationZip: '95401',
    harvestDate: '',
    availabilityWindow: 'Available now',
    notes: 'Untreated dimensional lumber and pallets from deconstruction jobs. Clean, no paint or treatment. Chipped on-site. Sonoma County pickup only.',
    photos: [],
    status: 'active',
    verified: false,
    createdAt: demoTimestamp('2026-02-05')
  }
];
