function demoTimestamp(dateStr) {
  return { toMillis: function () { return new Date(dateStr).getTime(); } };
}

window.LISTINGS = [
  {
    id: "cbx-201",
    producerUID: "demo-producer-201",
    producerName: "Sacramento Valley Carbon Co.",
    contactName: "Operations Team",
    contactEmail: "sales@sacvalleycarbon.com",
    state: "CA",
    zipcode: "95828",
    ein: "12-4589123",
    businessWebsite: "https://sacvalleycarbon.com",
    yearsInOperation: "6",
    equipmentType: "retort",
    pyroTech: "retort",
    annualCapacity: 900,
    feedstock: "Almond Shell",
    scorecard: {
      carbonContent: 74.5,
      pH: 8.2,
      moisture: 9.5,
      surfaceArea: 320,
      particleSize: "1-4mm",
      ashContent: 12.1,
      electricalConductivity: 0.8,
      labVerified: true
    },
    certifications: ["IBI Certified", "OMRI Listed"],
    pricePerTonne: 380,
    availableTonnes: 320,
    minOrderTonnes: 10,
    availableFrom: "2026-02-15",
    availableUntil: "2026-10-15",
    leadTimeDays: 7,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description: "Retort-produced almond shell biochar screened to a uniform 1–4mm profile. Suitable for orchard and vegetable operations across the valley.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-01-20")
  },
  {
    id: "cbx-202",
    producerUID: "demo-producer-202",
    producerName: "Willamette Charworks",
    contactName: "Lena Morales",
    contactEmail: "hello@willamettecharworks.com",
    state: "OR",
    zipcode: "97302",
    ein: "23-5891432",
    businessWebsite: "https://willamettecharworks.com",
    yearsInOperation: "4",
    equipmentType: "kiln",
    pyroTech: "kiln",
    annualCapacity: 420,
    feedstock: "Vine Pruning",
    scorecard: {
      carbonContent: 71.0,
      pH: 8.0,
      moisture: 8.2,
      surfaceArea: 260,
      particleSize: "1-5mm",
      ashContent: 13.5,
      electricalConductivity: 0.9,
      labVerified: true
    },
    certifications: ["OMRI Listed"],
    pricePerTonne: 560,
    availableTonnes: 110,
    minOrderTonnes: 5,
    availableFrom: "2026-03-01",
    availableUntil: "2026-08-31",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description: "Small-batch vineyard pruning biochar with a low ash profile and consistent particle size for high-value perennial crops.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-02-05")
  },
  {
    id: "cbx-203",
    producerUID: "demo-producer-203",
    producerName: "Delta Rice Biochar",
    contactName: "Marcus Lee",
    contactEmail: "info@deltaricebiochar.com",
    state: "CA",
    zipcode: "95991",
    ein: "34-6978123",
    businessWebsite: "https://deltaricebiochar.com",
    yearsInOperation: "3",
    equipmentType: "kiln",
    pyroTech: "kiln",
    annualCapacity: 650,
    feedstock: "Rice Husk",
    scorecard: {
      carbonContent: 66.8,
      pH: 7.7,
      moisture: 10.2,
      surfaceArea: 210,
      particleSize: "0.5-2mm",
      ashContent: 18.0,
      electricalConductivity: 1.2,
      labVerified: false
    },
    certifications: [],
    pricePerTonne: 320,
    availableTonnes: 280,
    minOrderTonnes: 10,
    availableFrom: "2026-04-01",
    availableUntil: "2026-11-30",
    leadTimeDays: 14,
    deliveryMethods: ["buyer_collects", "third_party_freight"],
    description: "Fine rice-husk biochar with high silica content. Ideal for broadacre applications and blending.",
    photos: [],
    status: "active",
    verified: false,
    createdAt: demoTimestamp("2026-02-18")
  },
  {
    id: "cbx-204",
    producerUID: "demo-producer-204",
    producerName: "North Coast Soil Carbon",
    contactName: "Erin Wallace",
    contactEmail: "team@northcoastsoilcarbon.com",
    state: "CA",
    zipcode: "95492",
    ein: "45-7219345",
    businessWebsite: "https://northcoastsoilcarbon.com",
    yearsInOperation: "5",
    equipmentType: "retort",
    pyroTech: "retort",
    annualCapacity: 520,
    feedstock: "Walnut Shell",
    scorecard: {
      carbonContent: 75.4,
      pH: 8.4,
      moisture: 7.4,
      surfaceArea: 345,
      particleSize: "1-3mm",
      ashContent: 11.0,
      electricalConductivity: 0.7,
      labVerified: true
    },
    certifications: ["California Organic"],
    pricePerTonne: 470,
    availableTonnes: 160,
    minOrderTonnes: 5,
    availableFrom: "2026-02-10",
    availableUntil: "2026-09-25",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects"],
    description: "Walnut shell biochar produced under a closed-loop orchard program. Clean, consistent, and ready for field application.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-01-30")
  },
  {
    id: "cbx-205",
    producerUID: "demo-producer-205",
    producerName: "Monterey Agrochar",
    contactName: "Carmen Diaz",
    contactEmail: "hello@montereyagrochar.com",
    state: "CA",
    zipcode: "93907",
    ein: "56-8345123",
    businessWebsite: "https://montereyagrochar.com",
    yearsInOperation: "2",
    equipmentType: "kiln",
    pyroTech: "kiln",
    annualCapacity: 380,
    feedstock: "Corn Stover",
    scorecard: {
      carbonContent: 63.5,
      pH: 7.6,
      moisture: 11.5,
      surfaceArea: 160,
      particleSize: "2-6mm",
      ashContent: 19.2,
      electricalConductivity: 1.6,
      labVerified: false
    },
    certifications: [],
    pricePerTonne: 295,
    availableTonnes: 220,
    minOrderTonnes: 10,
    availableFrom: "2026-05-01",
    availableUntil: "2026-12-15",
    leadTimeDays: 21,
    deliveryMethods: ["producer_delivers", "third_party_freight"],
    description: "Stover-derived biochar suitable for row crops and compost blending. Consistent bulk supply with 2–3 week lead time.",
    photos: [],
    status: "active",
    verified: false,
    createdAt: demoTimestamp("2026-03-01")
  },
  {
    id: "cbx-206",
    producerUID: "demo-producer-206",
    producerName: "Cascade Carbon Labs",
    contactName: "Ben Hart",
    contactEmail: "info@cascadecarbonlabs.com",
    state: "WA",
    zipcode: "98802",
    ein: "67-9456123",
    businessWebsite: "https://cascadecarbonlabs.com",
    yearsInOperation: "8",
    equipmentType: "continuous_reactor",
    pyroTech: "continuous_reactor",
    annualCapacity: 1050,
    feedstock: "Forest Thinning",
    scorecard: {
      carbonContent: 78.2,
      pH: 8.9,
      moisture: 6.8,
      surfaceArea: 280,
      particleSize: "2-6mm",
      ashContent: 9.5,
      electricalConductivity: 0.6,
      labVerified: true
    },
    certifications: ["IBI Certified"],
    pricePerTonne: 410,
    availableTonnes: 260,
    minOrderTonnes: 15,
    availableFrom: "2026-03-20",
    availableUntil: "2026-11-20",
    leadTimeDays: 10,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description: "Forest thinning biochar with high fixed carbon and low ash content. Ideal for long-term soil carbon applications.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-02-28")
  },
  {
    id: "cbx-207",
    producerUID: "demo-producer-207",
    producerName: "Klamath Basin Biochar",
    contactName: "Sophie Grant",
    contactEmail: "sales@klamathbiochar.com",
    state: "OR",
    zipcode: "97603",
    ein: "78-0567123",
    businessWebsite: "https://klamathbiochar.com",
    yearsInOperation: "5",
    equipmentType: "retort",
    pyroTech: "retort",
    annualCapacity: 620,
    feedstock: "Wood Chip",
    scorecard: {
      carbonContent: 72.9,
      pH: 8.3,
      moisture: 9.1,
      surfaceArea: 240,
      particleSize: "2-5mm",
      ashContent: 14.0,
      electricalConductivity: 0.9,
      labVerified: true
    },
    certifications: ["IBI Certified"],
    pricePerTonne: 360,
    availableTonnes: 190,
    minOrderTonnes: 10,
    availableFrom: "2026-04-05",
    availableUntil: "2026-12-01",
    leadTimeDays: 7,
    deliveryMethods: ["buyer_collects", "third_party_freight"],
    description: "Mixed softwood biochar screened for spreader compatibility. Consistent supply for regional buyers.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-03-10")
  },
  {
    id: "cbx-208",
    producerUID: "demo-producer-208",
    producerName: "Humboldt Coastal Char",
    contactName: "Raj Patel",
    contactEmail: "contact@humboldtchar.com",
    state: "CA",
    zipcode: "95501",
    ein: "89-1123456",
    businessWebsite: "https://humboldtchar.com",
    yearsInOperation: "7",
    equipmentType: "continuous_reactor",
    pyroTech: "continuous_reactor",
    annualCapacity: 780,
    feedstock: "Wood Chip",
    scorecard: {
      carbonContent: 82.0,
      pH: 9.1,
      moisture: 6.0,
      surfaceArea: 380,
      particleSize: "2-6mm",
      ashContent: 8.5,
      electricalConductivity: 0.5,
      labVerified: true
    },
    certifications: ["IBI Certified", "California Organic"],
    pricePerTonne: 520,
    availableTonnes: 140,
    minOrderTonnes: 5,
    availableFrom: "2026-01-20",
    availableUntil: "2026-09-30",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects"],
    description: "Premium coastal wood-chip biochar with high surface area and low moisture. Limited seasonal availability.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-01-12")
  },
  {
    id: "cbx-209",
    producerUID: "demo-producer-209",
    producerName: "Columbia Basin Biochar",
    contactName: "Olivia Chen",
    contactEmail: "team@columbiabasinbiochar.com",
    state: "OR",
    zipcode: "97814",
    ein: "90-2213456",
    businessWebsite: "https://columbiabasinbiochar.com",
    yearsInOperation: "3",
    equipmentType: "kiln",
    pyroTech: "kiln",
    annualCapacity: 500,
    feedstock: "Wheat Straw",
    scorecard: {
      carbonContent: 62.5,
      pH: 7.9,
      moisture: 12.5,
      surfaceArea: 140,
      particleSize: "2-6mm",
      ashContent: 20.0,
      electricalConductivity: 1.8,
      labVerified: false
    },
    certifications: [],
    pricePerTonne: 260,
    availableTonnes: 300,
    minOrderTonnes: 20,
    availableFrom: "2026-06-01",
    availableUntil: "2026-12-31",
    leadTimeDays: 14,
    deliveryMethods: ["producer_delivers"],
    description: "Wheat straw biochar produced after harvest season. Best suited for soil conditioning and compost blends.",
    photos: [],
    status: "active",
    verified: false,
    createdAt: demoTimestamp("2026-04-15")
  },
  {
    id: "cbx-210",
    producerUID: "demo-producer-210",
    producerName: "Tri-Cities Carbon",
    contactName: "Alex Rivera",
    contactEmail: "info@tricitiescarbon.com",
    state: "WA",
    zipcode: "99301",
    ein: "11-3456789",
    businessWebsite: "https://tricitiescarbon.com",
    yearsInOperation: "4",
    equipmentType: "retort",
    pyroTech: "retort",
    annualCapacity: 560,
    feedstock: "Corn Stover",
    scorecard: {
      carbonContent: 64.8,
      pH: 7.8,
      moisture: 13.0,
      surfaceArea: 150,
      particleSize: "2-6mm",
      ashContent: 18.5,
      electricalConductivity: 1.4,
      labVerified: true
    },
    certifications: ["OMRI Listed"],
    pricePerTonne: 280,
    availableTonnes: 240,
    minOrderTonnes: 10,
    availableFrom: "2026-05-10",
    availableUntil: "2026-11-15",
    leadTimeDays: 10,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description: "Corn stover char with moderate ash content. Available in bulk walking-floor deliveries across eastern Washington.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-03-22")
  },
  {
    id: "cbx-211",
    producerUID: "demo-producer-211",
    producerName: "Siskiyou Biochar Collective",
    contactName: "Meera Singh",
    contactEmail: "hello@siskiyoubiochar.com",
    state: "CA",
    zipcode: "96097",
    ein: "22-4567891",
    businessWebsite: "https://siskiyoubiochar.com",
    yearsInOperation: "6",
    equipmentType: "continuous_reactor",
    pyroTech: "continuous_reactor",
    annualCapacity: 840,
    feedstock: "Forest Thinning",
    scorecard: {
      carbonContent: 77.0,
      pH: 8.7,
      moisture: 7.0,
      surfaceArea: 260,
      particleSize: "2-5mm",
      ashContent: 10.5,
      electricalConductivity: 0.7,
      labVerified: true
    },
    certifications: ["OMRI Listed"],
    pricePerTonne: 395,
    availableTonnes: 210,
    minOrderTonnes: 15,
    availableFrom: "2026-03-05",
    availableUntil: "2026-12-05",
    leadTimeDays: 7,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description: "Forest thinning biochar produced in a continuous reactor with reliable supply for long-term contracts.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2026-02-12")
  }
];
