function demoTimestamp(dateStr) {
  return { toMillis: function () { return new Date(dateStr).getTime(); } };
}

window.LISTINGS = [
  {
    id: "cbx-001",
    producerUID: "demo-producer-001",
    producerName: "Valley Carbon Cooperative",
    contactName: "Operations Team",
    contactEmail: "info@valleycarboncooperative.com",
    state: "CA",
    zipcode: "93706",
    ein: "12-3456789",
    businessWebsite: "https://valleycarboncooperative.com",
    yearsInOperation: "6",
    equipmentType: "retort",
    pyroTech: "retort",
    annualCapacity: 1200,
    feedstock: "Almond Shell",
    scorecard: {
      carbonContent: 76.2,
      pH: 8.4,
      moisture: 7.9,
      surfaceArea: 355,
      particleSize: "1-4mm",
      ashContent: 11.6,
      electricalConductivity: 0.7,
      labVerified: true
    },
    certifications: ["IBI Certified", "California Organic"],
    pricePerTonne: 365,
    availableTonnes: 420,
    minOrderTonnes: 5,
    availableFrom: "2025-03-01",
    availableUntil: "2025-10-31",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "producer_delivers", "third_party_freight"],
    description:
      "We produce this lot from clean almond shell feedstock sourced within a 60-mile radius of our kiln facility. Our batch is screened for uniform particle size to support consistent field application and blending. Third-party lab results are updated each production run.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2025-02-01")
  },
  {
    id: "cbx-002",
    producerUID: "demo-producer-002",
    producerName: "Delta Pyro Materials",
    contactName: "Logistics Lead",
    contactEmail: "info@deltapyromaterials.com",
    state: "CA",
    zipcode: "95694",
    ein: "23-4567890",
    businessWebsite: "https://deltapyromaterials.com",
    yearsInOperation: "4",
    equipmentType: "kiln",
    pyroTech: "kiln",
    annualCapacity: 900,
    feedstock: "Rice Husk",
    scorecard: {
      carbonContent: 68.9,
      pH: 7.8,
      moisture: 9.2,
      surfaceArea: 298,
      particleSize: "0.5-2mm",
      ashContent: 15.3,
      electricalConductivity: 1.1,
      labVerified: true
    },
    certifications: ["OMRI Listed", "IBI Certified"],
    pricePerTonne: 310,
    availableTonnes: 260,
    minOrderTonnes: 5,
    availableFrom: "2025-04-15",
    availableUntil: "2025-11-15",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description:
      "We convert post-harvest rice husk into a fine, high-silica biochar designed for broadacre and paddy systems. Our operation maintains lot traceability from mill intake through bagging and bulk dispatch. Material is supplied loose bulk or super sacks based on your handling setup.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2025-03-10")
  },
  {
    id: "cbx-003",
    producerUID: "demo-producer-003",
    producerName: "Redwood Soil Carbon",
    contactName: "Production Manager",
    contactEmail: "info@redwoodsoilcarbon.com",
    state: "CA",
    zipcode: "95501",
    ein: "34-5678901",
    businessWebsite: "https://redwoodsoilcarbon.com",
    yearsInOperation: "7",
    equipmentType: "continuous_reactor",
    pyroTech: "continuous_reactor",
    annualCapacity: 700,
    feedstock: "Wood Chip",
    scorecard: {
      carbonContent: 81.4,
      pH: 8.9,
      moisture: 6.4,
      surfaceArea: 402,
      particleSize: "2-6mm",
      ashContent: 9.8,
      electricalConductivity: 0.5,
      labVerified: true
    },
    certifications: ["IBI Certified"],
    pricePerTonne: 520,
    availableTonnes: 180,
    minOrderTonnes: 5,
    availableFrom: "2025-05-01",
    availableUntil: "2025-12-20",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "third_party_freight"],
    description:
      "We manufacture this wood-chip char from FSC-aligned forest thinning residues and sawmill side streams. Our product is designed for long residence time and high porosity in perennial systems. We publish full scorecards and retain reserve samples for quality audits.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2025-04-12")
  },
  {
    id: "cbx-004",
    producerUID: "demo-producer-004",
    producerName: "Sonoma Circular Char",
    contactName: "Sales Desk",
    contactEmail: "info@sonomacircularchar.com",
    state: "CA",
    zipcode: "95403",
    ein: "45-6789012",
    businessWebsite: "https://sonomacircularchar.com",
    yearsInOperation: "3",
    equipmentType: "kiln",
    pyroTech: "kiln",
    annualCapacity: 350,
    feedstock: "Vine Pruning",
    scorecard: {
      carbonContent: 73.1,
      pH: 8.1,
      moisture: 8.8,
      surfaceArea: 336,
      particleSize: "1-5mm",
      ashContent: 12.9,
      electricalConductivity: 0.9,
      labVerified: true
    },
    certifications: ["California Organic"],
    pricePerTonne: 610,
    availableTonnes: 95,
    minOrderTonnes: 5,
    availableFrom: "2025-02-10",
    availableUntil: "2025-08-30",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "producer_delivers"],
    description:
      "We produce vine-pruning biochar from estate and neighboring vineyard blocks under a closed-loop program. This material is optimized for vineyard floor incorporation and compost blending. Seasonal production windows are reflected in our listed availability dates.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2025-01-25")
  },
  {
    id: "cbx-005",
    producerUID: "demo-producer-005",
    producerName: "Central Coast Nut Carbon",
    contactName: "Dispatch",
    contactEmail: "info@centralcoastnutcarbon.com",
    state: "CA",
    zipcode: "93111",
    ein: "56-7890123",
    businessWebsite: "https://centralcoastnutcarbon.com",
    yearsInOperation: "5",
    equipmentType: "retort",
    pyroTech: "retort",
    annualCapacity: 520,
    feedstock: "Walnut Shell",
    scorecard: {
      carbonContent: 74.6,
      pH: 8.3,
      moisture: 7.1,
      surfaceArea: 349,
      particleSize: "1-3mm",
      ashContent: 10.7,
      electricalConductivity: 0.8,
      labVerified: false
    },
    certifications: ["OMRI Listed", "California Organic"],
    pricePerTonne: 455,
    availableTonnes: 140,
    minOrderTonnes: 5,
    availableFrom: "2025-03-20",
    availableUntil: "2025-09-25",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "third_party_freight"],
    description:
      "We process cracked walnut shell fractions into a medium-grind biochar for diversified coastal farms. Our batches are blended to maintain stable pH and moisture targets for predictable field performance. Freight coordination is available for palletized and walking-floor deliveries.",
    photos: [],
    status: "active",
    verified: false,
    createdAt: demoTimestamp("2025-02-18")
  },
  {
    id: "cbx-006",
    producerUID: "demo-producer-006",
    producerName: "Foothill Biomass Exchange",
    contactName: "Operations",
    contactEmail: "info@foothillbiomassexchange.com",
    state: "CA",
    zipcode: "95667",
    ein: "67-8901234",
    businessWebsite: "https://foothillbiomassexchange.com",
    yearsInOperation: "8",
    equipmentType: "continuous_reactor",
    pyroTech: "continuous_reactor",
    annualCapacity: 1100,
    feedstock: "Wood Chip",
    scorecard: {
      carbonContent: 79.3,
      pH: 8.6,
      moisture: 6.9,
      surfaceArea: 371,
      particleSize: "2-5mm",
      ashContent: 10.2,
      electricalConductivity: 0.6,
      labVerified: true
    },
    certifications: ["IBI Certified", "OMRI Listed", "California Organic"],
    pricePerTonne: 390,
    availableTonnes: 230,
    minOrderTonnes: 5,
    availableFrom: "2025-04-01",
    availableUntil: "2025-11-30",
    leadTimeDays: 0,
    deliveryMethods: ["buyer_collects", "producer_delivers", "third_party_freight"],
    description:
      "We produce this material from mixed hardwood and softwood chips generated through fuel-reduction projects in the foothills. The char is screened for spreader compatibility and low fines content. We support recurring contracts for orchards and annual row-crop programs.",
    photos: [],
    status: "active",
    verified: true,
    createdAt: demoTimestamp("2025-03-28")
  }
];
